### ISSUE TITLE
Game lua crash when crafting with Factory Crafting Station

### ISSUE THREAD

**Issue by cwitty** [Sopel97/composite_factories_base#12]
I decided to try Composite Factories in my PyBlock playthrough.  I made a Factory Crafting Station, and dumped in all the materials for a composite-factory-electricity-1-a-generator; the corresponding ingredient squares lit up green, and so did the crafting icon.  But when I clicked on the crafting icon, it crashed with this error message:

```
The mod Composite Factories: Base (1.0.3) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event composite_factories_base::on_gui_click (ID 1)
__composite_factories_base__/control.lua:629: attempt to call global 'is_recipe_researched' (a nil value)
stack traceback:
	__composite_factories_base__/control.lua:629: in function 'try_craft_inside_inventory'
	__composite_factories_base__/control.lua:679: in function 'handler'
	__composite_factories_base__/control.lua:970: in function <__composite_factories_base__/control.lua:967>
```

**Comment by Sopel97** [comment]
Thanks for reporting this. The `is_recipe_researched` is indeed missing in the released version. I've fixed this and will publish updated archive on the mod portal soon.
