### ISSUE TITLE
composite generators don't work (with fix)

### ISSUE THREAD

**Issue by cwitty** [Sopel97/composite_factories_base#13]
I tried to add a composite-factory-electricity-1-b-generator to my power network.  The network showed the factory icon in the "Electric network info"/"Production" tab, but it was showing a production of 0W; and when I disconnected it from existing generators, it still showed 0W and did not power a radar that I placed.  Also, there was a red "no power" icon on the composite generator.

I compared the prototype information of the composite-factory-electricity-1-b-generator with an Infinity Accumulator (from Editor Extensions), and noticed one difference: the (working) Infinity Accumulator had a non-zero buffer capacity in its energy source, and your composite generator had a zero buffer capacity.  (To see the prototype information in-game, hover over the entity and press Control-Shift-F .)  So I changed composite_factories_base_1.0.3/data.lua to change the buffer capacity.  Then, the generator I had placed still had a zero buffer capacity; but picking it up and re-placing it fixed that problem.  After I did that, the generator had a non-zero buffer capacity, and was able to power my network.

The exact change I made was to change line 1225 of data.lua from:
```
                buffer_capacity = nil,
```
to:
```
                buffer_capacity = args.energy_production,
```

**Comment by Sopel97** [comment]
Thanks for reporting this. This seems to be an omission of mine. When generators are created the `buffer_capacity` is provided, it was just not being used to create the prototy. I've issued a fix and will put it on the mod portal soon.
