### ISSUE TITLE
Miniloaders don't show properly in selection tool

### ISSUE THREAD

**Issue by Krydax** [Sopel97/composite_factories_base#22]
This is from a message another player sent to me, but apparently the selection tool when used on miniloaders returns the invisible inserter entities, rather than the miniloader entities. Given the prevalent use of miniloaders with pY players especially, could be worth investigating!

**Comment by Sopel97** [comment]
Partially fixed with dev 1.5. Counts will still be incorrect for miniloaders though, because they use more than one entity per miniloader, and do some trickery to update blueprints.
