### ISSUE TITLE
Cannot Build Deconstructor Building

### ISSUE THREAD

**Issue by Krydax** [Sopel97/composite_factories_base#26]
![image](https://user-images.githubusercontent.com/93162034/156075090-71a85b8a-c0de-4d98-99b7-15411809bbf5.png)

**Comment by Krydax** [comment]
![image](https://user-images.githubusercontent.com/93162034/156075124-9d28365d-4aa1-475b-b58a-87163d8ce374.png)

**Comment by Sopel97** [comment]
Fixed in dev 1.5
